version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-container
    environment:
      POSTGRES_USER: tourist_admin
      POSTGRES_PASSWORD: Diana3112
      POSTGRES_DB: tourist_destinations_db
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  demo-app:
    build:
      context: .
    ports:
      - "8084:8084"
    container_name: demo-app-container
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tourist_destinations_db
      SPRING_DATASOURCE_USERNAME: tourist_admin
      SPRING_DATASOURCE_PASSWORD: Diana3112
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_SHOW_SQL: true
      SPRING_DATA_REST_BASE_PATH: /api
      SERVER_PORT: 8084
      SPRINGDOC_API_DOCS_PATH: /v3/api-docs
      SPRINGDOC_SWAGGER_UI_OPERATIONSSORTER: method
      SERVER_ADDRESS: 0.0.0.0
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
